### PR TITLE
APICallCounter passed

### PR DESCRIPTION
**Pull request by chasmkhasan**
API Call Counter Stattistices

### CODE REVIEW

**Review by Rezaeskandar — APPROVED** [review]
LGTM

**Comment by Md-Ruhul-Amin-Rony** [comment]
lgtm

**Review by Md-Ruhul-Amin-Rony — APPROVED** [review]
ok

**Review by chasmkhasan — COMMENTED** [review]
Plz check it again

**Review by Md-Ruhul-Amin-Rony — COMMENTED** [review]
ok

**Pull request merged**
