### PR TITLE
Added first Xunit tests To stockholm weather 

### PR DESCRIPTION
**Pull request by Rezaeskandar**

### CODE REVIEW

**Comment by Rezaeskandar** [comment]
LGTM

**Comment by Rezaeskandar** [comment]
LGTM

**Review by Md-Ruhul-Amin-Rony — COMMENTED** [review]
ok

**Review by chasmkhasan — COMMENTED** [review]
Looks Goods

**Review by Md-Ruhul-Amin-Rony — COMMENTED** [review]
LGTM

**Review by chasmkhasan — COMMENTED** [review]
Look Goods

**Review by chasmkhasan — APPROVED** [review]

**Review by Md-Ruhul-Amin-Rony — APPROVED** [review]

**Review by Rezaeskandar — COMMENTED** [review]
LGTM

**Comment by Md-Ruhul-Amin-Rony** [comment]
ok

**Pull request merged**
